feature(backend signup): create user in thedatabase
nkalyesubula/AndaApp pull request #17
Opened 2019-07-23 13:18 UTC by habinezadalvan

### What does this PR do?
- Create a user in the database by sign up.
### Description of Task to be completed?
- Create Users' model and migration.
- Created a function that creates the user.
- Created a function that encrypts the password and the other one that creates the token.
- Created a middleware for authentication. 
### How should this be manually tested?
- Clone the repo, then run <npm install>, run<npm run dev>, the use postman to test sign up endpoint
### Any background context you want to provide?
- none
### What are the relevant pivotal tracker stories?
67437498(https://www.pivotaltracker.com/story/show/167437498);
### Screenshots (if appropriate)
<img width="1281" alt="Screen Shot 2019-07-23 at 15 17 41" src="https://user-images.githubusercontent.com/45101716/61715285-11943480-ad5d-11e9-8261-05cda5213538.png">

### Questions:
-None

2019-07-23 13:51 UTC, nshutijonathan commented on src/controllers/users/signup.js
> +class SignClass{
Would You mind to use SignupClass instead SignClass

2019-07-23 14:20 UTC, minega25 requested changes
Great Job. My reviews are included

2019-07-23 14:20 UTC, minega25 commented on src/controllers/users/signup.js
> +import userModel from '../../models/index'
This can be resolved by installing `babel-eslint` 
Then include below code in your eslintrc file
`{
  "parser": "babel-eslint",
  "parserOptions": {
    "sourceType": "module",
    "allowImportExportEverywhere": true
  }
}`

2019-07-23 14:20 UTC, minega25 commented on src/helpers/bcryptHash.js
> +class secureCredentials {
Why did you choose to use a class here?

2019-07-23 14:20 UTC, minega25 commented on src/controllers/users/signup.js
> +            res.status(201).json({
I suggest we use the `return` key word to end the request processing cycle at this point.

2019-07-23 14:20 UTC, minega25 commented on src/middleware/auth.js
> +const authantication = (req, res, next) =>{
The request handler has a spelling mistake

2019-07-23 14:20 UTC, minega25 commented on src/routes/users.js
> +router.post('/api/signup', userController.signup);
I suggest we use a variable that holds the base url.

2019-07-23 15:15 UTC, Anguandia commented on src/routes/users.js
> +router.post('/api/signup', userController.signup);
I would rather we logically group routes with the same general pattern in one file and in the server setup file we declare the general url pattern as a prefix with app.use

2019-07-24 07:23 UTC, Anguandia reviewed
Hi, would you consider renaming your controller/users to controllers and instead create the users file inside the controllers directory?

2019-07-24 16:30 UTC, nkalyesubula requested changes

2019-07-24 16:30 UTC, nkalyesubula commented on src/controllers/users/signup.js
> +      if (email.length !== 0) {
Would you consider refactoring "!=="  to "!=" or  ">0" as this is the right comparison operators.

2019-07-24 16:30 UTC, nkalyesubula commented on src/controllers/users/signup.js
> +            const { id, firstname, lastname, email } = user;
Best practice: the variable name comes before the assignment operator.  Consider using const user = {id,firstname...}

2019-07-24 16:30 UTC, nkalyesubula commented on src/helpers/validations/usersValidations.js
> +class UserValidationsClass {
Could you use UserValidation instead of UserValidationClass

2019-07-24 16:30 UTC, nkalyesubula commented on src/test/users-tests.js
> +chai.should();
You have two libraries achieving the same thing. could you please considering using one

2019-07-24 18:06 UTC, nkalyesubula approved these changes

2019-07-24 18:07 UTC, merged